const menu=document.querySelector(".menu"),links=document.querySelector(".links");menu.addEventListener("click",()=>{const o=links.classList.toggle("open");menu.setAttribute("aria-expanded",o)});document.querySelectorAll(".links a").forEach(a=>a.addEventListener("click",()=>links.classList.remove("open")));document.getElementById("year").textContent=new Date().getFullYear();

const reveals=document.querySelectorAll(".reveal");const observer=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting)e.target.classList.add("visible")}),{threshold:.1});reveals.forEach(el=>observer.observe(el));

const card=document.getElementById("configCard"),qty=document.getElementById("quantity"),estimate=document.getElementById("estimate"),unit=document.getElementById("unitPrice");
const base={50:129,100:189,250:389,500:679,1000:1199};
const fields=[["nameInput","previewName"],["companyInput","previewCompany"],["titleInput","previewTitle"],["phoneInput","previewPhone"],["webInput","previewWeb"]];
fields.forEach(([input,output])=>document.getElementById(input).addEventListener("input",e=>document.getElementById(output).textContent=e.target.value||" "));
document.querySelectorAll('input[name="finish"]').forEach(r=>r.addEventListener("change",e=>{card.className=`metal-card config-card finish-${e.target.value}`;updatePrice()}));
["quantity","backSide","qrCode","rush"].forEach(id=>document.getElementById(id).addEventListener("change",updatePrice));
document.getElementById("qrCode").addEventListener("change",e=>document.getElementById("qrDemo").classList.toggle("hidden",!e.target.checked));
function updatePrice(){let total=base[qty.value];if(document.getElementById("backSide").checked)total+=Number(qty.value)*.38;if(document.getElementById("qrCode").checked)total+=25;if(document.getElementById("rush").checked)total*=1.25;total=Math.round(total);estimate.textContent=`$${total.toLocaleString()}`;unit.textContent=`$${(total/Number(qty.value)).toFixed(2)} per card`}
document.getElementById("useConfiguration").addEventListener("click",()=>{document.getElementById("quoteQuantity").value=qty.value;document.getElementById("quoteFinish").value=document.querySelector('input[name="finish"]:checked').value.replace(/^./,c=>c.toUpperCase());document.getElementById("quote").scrollIntoView({behavior:"smooth"})});
document.getElementById("quoteForm").addEventListener("submit",e=>{e.preventDefault();const d=new FormData(e.target),subject=encodeURIComponent(`Metal Card Quote Request - ${d.get("name")}`),body=encodeURIComponent(`Name: ${d.get("name")}\nCompany: ${d.get("company")}\nEmail: ${d.get("email")}\nPhone: ${d.get("phone")}\nQuantity: ${d.get("quantity")}\nFinish: ${d.get("finish")}\n\nProject details:\n${d.get("details")}`);location.href=`mailto:orders@defydesign.store?subject=${subject}&body=${body}`});
updatePrice();